### ISSUE TITLE
Too Many recursion

### ISSUE THREAD

**Issue by dsamit** [evoluteur/colorpicker#24]
I tried to use evol.colorpicker for 3 input elements.
I did bind both the events (change.color & mouseover.color) to all three elements.
Which causes the error "to much recursion".

But when i tried with only two of these three then its working fine.
And for separate all of three are working fine but at one time if using all three is giving error "to much recursion".

Please help me out.
Thanks
Amit

**Comment by evoluteur** [comment]
I can't reproduce the problem. I bound 10 colorPickers on the same page and I did not get the recursion error. It's working for me (w/ Firefox 38.0.1 or Chrome 43). 

To try it, just paste the code bellow in the project index.html script.

	$('.colorPicker,#cpDiv,#cpDiv2').not('#cp1')
		.on('change.color', function(evt, color){
			$('body').css('background-color',color);
		})
		.on('mouseover.color', function(evt, color){
			if(color){
				$('body').css('background-color',color);
			}
		});

The recursion error may be caused by the code handling the event which may set the color which trigger the event again and therefore create an infinite loop.

**Comment by dsamit** [comment]
Hi @evoluteur,

Thanks for the reply.

I got the issue resolved by placing a check for every change color event.

Thanks
Amit
